Add `getValuesMessage` option for `assertType`
sindresorhus/is pull request #132
Opened 2021-04-11 16:42 UTC by scraggo

This PR addresses #131 

Approach: Add an options object to `assertType`. This allows a custom failure message from the calling code. It's a function that returns a string and passed in as `getValuesMessage` to the options object.

What do you think of the approach?

2021-04-19 09:52 UTC, sindresorhus requested changes

2021-04-19 09:52 UTC, sindresorhus commented on source/index.ts
> +const assertType = (condition: boolean, description: string, value: unknown, options: { getValuesMessage?: () => string } = {}): asserts condition => {
I don't see the point in nesting it in an options object. We're only using this internally. Can just be a normal argument.

2021-04-19 09:53 UTC, sindresorhus commented
Does the issue also apply to `.all`? If so, we should fix it there too.

2021-04-21 17:08 UTC, scraggo commented
@sindresorhus I tried a slightly different approach in my latest push and applied it to `.all` as well.

I decided to keep the options object for this approach because it's now a boolean flag. `{multipleValues: true}` is more readable in my opinion than a bare boolean. This isn't a strong opinion and it's easily changed if you disagree 😄

2021-04-22 09:00 UTC, merged

2021-04-22 09:00 UTC, sindresorhus commented
Thanks :)