Added is.enumCase and assert.enumCase
sindresorhus/is pull request #150
Opened 2022-01-16 00:51 UTC by olivierbeaulieu

Implements https://github.com/sindresorhus/is/issues/148

Turns out typing this correctly was a bit trickier than I initially expected, since enums are both a value and a type.

Given this:

```ts
enum Direction {
	Asc = 'asc',
	Desc = 'desc'
}
const input: string = 'asc';
assert.enumCase(input, Direction);
```

If `assert.enumCase` was typed to return `asserts value is T` (T being the inferred type of `Direction`), the asserted type of `input` would become `string & typeof Direction`, which is no good.

Typing it as `asserts value is T[keyof T]` instead did the trick.

2022-01-16 07:47 UTC, sindresorhus requested changes

2022-01-16 07:47 UTC, sindresorhus commented on readme.md
> +}
```suggestion
enum Direction {
	Ascending = 'ascending',
	Descending = 'descending'
}
```

Nitpick

2022-01-16 07:47 UTC, sindresorhus commented on readme.md
> +
```suggestion
**TypeScript-only**
```

2022-01-16 18:31 UTC, olivierbeaulieu commented
Suggestions, applied, thanks!

2022-01-17 05:55 UTC, merged

2022-01-18 04:19 UTC, papb commented
Hello, I think there should have been a test case to verify that `assert.enumCase` really narrows the type, shouldn't it? The added test is runtime-only...

2022-01-18 15:43 UTC, olivierbeaulieu commented
I thought about added this in - but I noticed that none of the other test suites did the same, so I left it out. Happy to add this in if the maintainers see the value.